### ISSUE TITLE
Possible nullreference exception, enable nullable and check for null

### ISSUE THREAD

**Issue by siliwan** [ItsOKayCZ/self-driving#41]
https://github.com/ItsOKayCZ/self-driving/blob/9e6d907ee91c3ca64782418882902801e63e95c4/Assets/Scripts/TrackGenerator.cs#L39

**Comment by ItsOKayCZ** [comment]
Even though a nullreference could happen here, while running the simulation for hours and hours an error never occurred here. The gameobject is always assigned in the [PlacePiece](https://github.com/ItsOKayCZ/self-driving/blob/9e6d907ee91c3ca64782418882902801e63e95c4/Assets/Scripts/TrackGenerator.cs#L97) method. :)
